server:
  port: 8084

spring:
  application:
    name: notification-service
  notification:
    email:
      recipient: sairam03feb2003@gmail.com

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/kafka_notify
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  kafka:
    consumer:
      bootstrap-servers: host.docker.internal:9092,host.docker.internal:9094
      group-id: notification-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        max.poll.records: 10
        max.poll.interval.ms: 300000
        session.timeout.ms: 10000
        heartbeat.interval.ms: 3000
        spring.json.trusted.packages: "*"

---
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: cut

logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: ete

logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: drt

logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    root: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: false

logging:
  level:
    root: WARN